services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - uploads:/app/uploads
    environment:
      - FLASK_ENV=development
    restart: always

volumes:
  uploads: